# Generated by Django 5.2.4 on 2025-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('type', models.TextField()),
                ('instruction', models.TextField()),
                ('searches', models.IntegerField()),
            ],
        ),
    ]
