# Generated by Django 5.2.4 on 2025-07-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='type',
        ),
    ]
