# Generated by Django 5.2.4 on 2025-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_drink_image_remove_drink_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='searches',
            field=models.IntegerField(default=0),
        ),
    ]
